"""email

Revision ID: 68012c521b57
Revises: c2def8fcd26d
Create Date: 2022-09-27 18:49:36.066313

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68012c521b57'
down_revision = 'c2def8fcd26d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('email', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'email')
    # ### end Alembic commands ###
